### ISSUE TITLE
Old Contact Details From SimpleMobileTools

### ISSUE THREAD

**Issue by Maxitendo1** [Goodwy/File-Manager#1]
In Settings -> About -> Frequently Asked Questions, it says the old email adress and old github link from the SimpleMobileTools.![Screenshot_20240426-224727.png](https://github.com/Goodwy/File-Manager/assets/136966318/1925cafe-ce6e-4229-9797-1cc46a290870)

**Comment by Goodwy** [comment]
Thank you, corrected.
